version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - /data/db:/data/db
    logging:
      driver: none

  api:
    build:
      context: api
    restart: always
    depends_on:
      - mongo
    volumes:
      - api-build:/opt/application/api-build
      - /data/demo-storage:/data/storage
    env_file: api/production.env
    environment:
      API_SECRET: ${API_SECRET}
    healthcheck:
      test: curl -s -w '%{http_code}' http://localhost:3000/api/describe
      timeout: 5s
      interval: 10s

  web:
    build:
      context: web
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - api-build:/opt/application/api
      - web-build:/var/www/html

  nginx:
    build:
      context: nginx
    restart: always
    depends_on:
      - web
    ports:
      - 8081:80
    volumes:
      - web-build:/var/www/html

  cron:
    build:
      context: cron
    restart: always
    depends_on:
      - api
    environment:
      API_SECRET: ${API_SECRET}

volumes:
  api-build:
  web-build:

